/*
 * This file is generated by jOOQ.
 */
package ru.red.four.authorizationservice.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.red.four.authorizationservice.jooq.tables.Users;
import ru.red.four.authorizationservice.jooq.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UsersRecord> PK_USERS = Internal.createUniqueKey(Users.USERS, DSL.name("pk-users"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> UQ_USERNAME = Internal.createUniqueKey(Users.USERS, DSL.name("uq-username"), new TableField[] { Users.USERS.USERNAME }, true);
}
