/*
 * This file is generated by jOOQ.
 */
package ru.red.four.authorizationservice.jooq;


import ru.red.four.authorizationservice.jooq.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>USERS</code>.
     */
    public static final Users USERS = Users.USERS;
}
